apiVersion: v2
name: sol
description: A Helm chart for SelbstorganisiertesLernenCMS (SOL) - Next.js with Payload CMS
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - nextjs
  - payload-cms
  - cms
maintainers:
  - name: Lukas
